---
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_output
  changed_when: "'kubeadm join' in kubeadm_output.stdout"

- name: Set up kubeconfig for the ubuntu user
  become: yes
  become_user: ubuntu
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    creates: /home/ubuntu/.kube/config

- name: Apply Flannel network
  become: yes
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

- name: Save kubeadm join command
  command: kubeadm token create --print-join-command
  register: join_command
  changed_when: true

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command.stdout }}"

- name: Copy join command to local file
  local_action:
    module: copy
    content: "{{ join_command }}"
    dest: "./join-command"
