apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000  # You can choose a port in the range 30000-32767
